#!/usr/bin/env bash
#
# Build an optimized muzaiten binary and package it as a distributable tarball
# (used for Codeberg release artifacts and the muzaiten-bin AUR package).
#
# Last.fm credentials are injected here at build time and never committed.
# Provide them via the environment or a local .env file:
#
#     MUZAITEN_LASTFM_API_KEY=...  MUZAITEN_LASTFM_SHARED_SECRET=...  ./packaging/build-release.sh
#
# An empty value simply leaves Last.fm inactive until the user configures their
# own key in the app. See docs/distribution.md for the key-embedding threat
# model — the values are compile-time XOR-obfuscated but recoverable, so only
# the maintainer-built -bin/release artifacts should carry real keys.
set -euo pipefail

# Hidden dev option (intentionally absent from usage below): after building the
# tarball, also emit a local-file PKGBUILD under dist/aur-dev/muzaiten-dev/ that
# installs from that tarball instead of a Codeberg release URL. It lets the
# prebuilt-dist (muzaiten-bin) packaging be test-built with makepkg locally
# before the artifact is uploaded and the upstream PKGBUILD is bumped. Enable
# with --dev-pkgbuild or DEV_PKGBUILD=1. See docs/distribution.md.
DEV_PKGBUILD="${DEV_PKGBUILD:-0}"

usage() {
    cat <<'USAGE'
Usage: packaging/build-release.sh

Build an optimized muzaiten binary and package it as a distributable tarball
under dist/ (+ .sha256) for Codeberg releases and the muzaiten-bin AUR package.

Configuration (environment or a local .env):
  MUZAITEN_LASTFM_API_KEY, MUZAITEN_LASTFM_SHARED_SECRET  embedded Last.fm creds
  PREFIX     install prefix baked into the tarball tree (default /usr)
  BUILD_DIR  build directory (default build-release)
  JOBS       parallel build jobs (default: nproc)
USAGE
}

for arg in "$@"; do
    case "$arg" in
        --dev-pkgbuild) DEV_PKGBUILD=1 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "error: unknown argument '$arg'" >&2; usage >&2; exit 2 ;;
    esac
done

# Emit dist/aur-dev/muzaiten-dev/{PKGBUILD,.SRCINFO,<tarball>} — a muzaiten-bin
# clone whose source is the local tarball, for `makepkg` testing before publish.
generate_dev_pkgbuild() {
    local tarball="$1" version="$2" arch="$3"
    local tarball_name outdir sha
    tarball_name="$(basename "$tarball")"
    outdir="dist/aur-dev/muzaiten-dev"
    sha="$(cut -d' ' -f1 < "${tarball}.sha256")"

    mkdir -p "$outdir"
    # makepkg resolves protocol-less sources next to the PKGBUILD, so place the
    # freshly built tarball there.
    cp -f "$tarball" "$outdir/$tarball_name"

    cat > "$outdir/PKGBUILD" <<PKGBUILD
# DEV/TEST package generated by packaging/build-release.sh --dev-pkgbuild.
# Mirrors muzaiten-bin but installs from the local tarball beside this file, so
# the prebuilt-dist packaging can be validated with makepkg before the artifact
# is uploaded and the upstream muzaiten-bin PKGBUILD is bumped. Do not publish.
pkgname=muzaiten-dev
pkgver=${version}
pkgrel=1
pkgdesc="Native music player for local libraries (local dev build for packaging tests)"
arch=('${arch}')
url="https://codeberg.org/11xx/muzaiten"
license=('Unlicense')
depends=('qt6-base' 'qt6-multimedia' 'taglib' 'gstreamer' 'gst-plugins-base-libs' 'glib2' 'zstd')
optdepends=('gst-plugins-good: extra audio decoders and sinks'
            'gst-plugin-pipewire: PipeWire audio output'
            'gst-plugins-bad: additional codecs (e.g. Musepack, APE)'
            'mpd: browse an MPD library alongside local sources')
provides=('muzaiten')
conflicts=('muzaiten' 'muzaiten-bin' 'muzaiten-git')
options=('!strip')  # build-release.sh already strips the binary
source=("muzaiten-${version}-\${CARCH}.tar.zst")
sha256sums=('${sha}')

package() {
    # Prefixed tree (usr/bin, usr/share/...) staged by build-release.sh.
    tar -C "\$pkgdir" -xf "muzaiten-${version}-\${CARCH}.tar.zst"
    # Re-home the license directory under this package's name.
    if [[ -d "\$pkgdir/usr/share/licenses/muzaiten" ]]; then
        mv "\$pkgdir/usr/share/licenses/muzaiten" "\$pkgdir/usr/share/licenses/\$pkgname"
    fi
}
PKGBUILD

    if command -v makepkg >/dev/null 2>&1; then
        ( cd "$outdir" && makepkg --printsrcinfo > .SRCINFO )
    else
        echo ">> makepkg not found; skipped .SRCINFO generation."
    fi

    echo ">> Wrote $outdir/PKGBUILD (local-file dev package)"
    echo ">> Test-build it with: ( cd $outdir && makepkg -f )"
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# Load .env (KEY=VALUE lines) if present, without echoing secrets.
if [[ -f .env ]]; then
    set -a
    # shellcheck disable=SC1091
    . ./.env
    set +a
fi

BUILD_DIR="${BUILD_DIR:-build-release}"
PREFIX="${PREFIX:-/usr}"
JOBS="${JOBS:-$(nproc)}"
: "${MUZAITEN_LASTFM_API_KEY:=}"
: "${MUZAITEN_LASTFM_SHARED_SECRET:=}"

if [[ -n "$MUZAITEN_LASTFM_API_KEY" ]]; then
    echo ">> Embedding a Last.fm API key (obfuscated)."
else
    echo ">> No Last.fm key provided; the build will ship without default credentials."
fi

echo ">> Configuring release build in '$BUILD_DIR'"
cmake -S . -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
    -DBUILD_TESTING=OFF \
    -DMUZAITEN_LASTFM_API_KEY="$MUZAITEN_LASTFM_API_KEY" \
    -DMUZAITEN_LASTFM_SHARED_SECRET="$MUZAITEN_LASTFM_SHARED_SECRET"

echo ">> Building"
cmake --build "$BUILD_DIR" -j "$JOBS"

# Version derived the same way as cmake/MuzaitenVersion.cmake.
day="$(TZ=UTC0 git show -s --date=format-local:%Y-%m-%d --format=%cd HEAD)"
n="$(TZ=UTC0 git rev-list --count --since="${day}T00:00:00" --until="${day}T23:59:59" HEAD)"
version="${day//-/.}.${n}.g$(git rev-parse --short HEAD)"
arch="$(uname -m)"

stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT

DESTDIR="$stage" cmake --install "$BUILD_DIR" --prefix "$PREFIX" >/dev/null
# Strip symbols: smaller, and removes the obfuscated-blob symbol names.
strip --strip-unneeded "$stage/$PREFIX/bin/muzaiten"
install -Dm644 UNLICENSE "$stage/$PREFIX/share/licenses/muzaiten/UNLICENSE"

mkdir -p dist
tarball="dist/muzaiten-${version}-${arch}.tar.zst"
tar --zstd -C "$stage" -cf "$tarball" .
( cd dist && sha256sum "$(basename "$tarball")" > "$(basename "$tarball").sha256" )

echo ">> Wrote $tarball"
echo ">> Wrote ${tarball}.sha256"
echo ">> Contents:"
tar -tf "$tarball" | sed 's/^/     /'

if [[ "$DEV_PKGBUILD" == 1 ]]; then
    if [[ "$PREFIX" != "/usr" ]]; then
        echo ">> WARNING: --dev-pkgbuild mirrors the prebuilt-dist package, whose" >&2
        echo ">>          package() extracts a usr/ tree, but PREFIX=$PREFIX here." >&2
        echo ">>          Rebuild with PREFIX=/usr for a faithful test." >&2
    fi
    generate_dev_pkgbuild "$tarball" "$version" "$arch"
fi
