set(MUZAITEN_PROJECT_VERSION "0.0.0")
set(MUZAITEN_VERSION_FALLBACK "0.0.0.unknown")
set(MUZAITEN_VERSION "${MUZAITEN_VERSION_FALLBACK}")

find_package(Git QUIET)
if(Git_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" show -s --format=%cd --date=format:%Y.%m.%d.%H%M%S HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.."
        RESULT_VARIABLE MUZAITEN_GIT_DATE_RESULT
        OUTPUT_VARIABLE MUZAITEN_GIT_DATE
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.."
        RESULT_VARIABLE MUZAITEN_GIT_SHA_RESULT
        OUTPUT_VARIABLE MUZAITEN_GIT_SHA
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" diff-index --quiet HEAD --
        WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.."
        RESULT_VARIABLE MUZAITEN_GIT_MODIFIED_RESULT
        OUTPUT_QUIET
        ERROR_QUIET
    )

    if(MUZAITEN_GIT_DATE_RESULT EQUAL 0 AND MUZAITEN_GIT_SHA_RESULT EQUAL 0
       AND NOT MUZAITEN_GIT_DATE STREQUAL "" AND NOT MUZAITEN_GIT_SHA STREQUAL "")
        set(MUZAITEN_PROJECT_VERSION "${MUZAITEN_GIT_DATE}")
        set(MUZAITEN_VERSION "${MUZAITEN_GIT_DATE}.g${MUZAITEN_GIT_SHA}")
        if(MUZAITEN_GIT_MODIFIED_RESULT EQUAL 1)
            string(APPEND MUZAITEN_VERSION "+modified")
        endif()
    endif()
endif()
